services:
  - type: web
    name: lideta-woreda-3-inspection
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OWNER_USERNAME
        sync: false
      - key: OWNER_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true